### ISSUE TITLE
I installed this gem and found blank `activestorage/dropbox/dropbox.rb` file

### ISSUE THREAD

**Issue by ashishprajapati** [abhinavmsra/activestorage-dropbox#1]
Hello @abhinavmsra 

I guess this gem `activestorage-dropbox` is not useful for supporting the dropbox with activestorage.  I installed the gem and found blank file `activestorage/dropbox/dropbox.rb`. I am also seeing this file https://github.com/abhinavmsra/activestorage-dropbox/blob/master/lib/activestorage/dropbox.rb and it's just blank.  

![Screenshot 2019-03-19 at 2 53 17 AM](https://user-images.githubusercontent.com/5468981/54564710-7a0b8780-49f2-11e9-9e68-0650a503bf34.png)

**Comment by ashishprajapati** [comment]
@abhinavmsra  Gems are for public use and we should build a perfect and useful gem that should at least work. It's not worth pushing the blank library files within the gem :) 

https://bundler.io/v2.0/guides/creating_gem.html
https://guides.rubygems.org/make-your-own-gem/

**Comment by abhinavmsra** [comment]
Hello @ashishprajapati I am just getting started with this gem. Sorry for the confusion
